import { Noto_Sans } from "next/font/google"
import "./globals.css"

const noto = Noto_Sans({ subsets: ["cyrillic", "cyrillic-ext", "devanagari", "greek", "greek-ext", "latin", "latin-ext", "vietnamese"] })

export const metadata = {
  title: "Language Learning App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  )
}
