import { Noto_Sans } from "next/font/google"
import "./globals.css"
import AuthProvider from "@/components/Providers/AuthProvider"
import { ContextProvider } from "@/context/contextProvider"

const noto = Noto_Sans({
	subsets: [
		"cyrillic",
		"cyrillic-ext",
		"devanagari",
		"greek",
		"greek-ext",
		"latin",
		"latin-ext",
		"vietnamese"
	]
})

export const metadata = {
	title: "Language Learning App",
	description: "Generated by create next app"
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={noto.className}>
				<ContextProvider>
					<AuthProvider>{children}</AuthProvider>
				</ContextProvider>
			</body>
		</html>
	)
}
